# Generated by Django 2.1.4 on 2019-01-21 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_apps', '0003_auto_20190121_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
                ('text', models.TextField()),
                ('related_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_apps.Post')),
            ],
        ),
    ]
