# Generated by Django 2.1.4 on 2019-01-21 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_apps', '0004_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='related_post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
