# Generated by Django 2.1.4 on 2019-01-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_apps', '0007_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published',
            field=models.CharField(default='29 January 2019, 12:50 PM', max_length=100),
        ),
    ]
