# Generated by Django 2.1.4 on 2019-01-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_apps', '0008_post_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published',
        ),
        migrations.AddField(
            model_name='post',
            name='publish_time',
            field=models.CharField(default='29 January 2019, 12:52 PM', max_length=100),
        ),
    ]
