# Generated by Django 2.1.4 on 2019-01-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_apps', '0009_auto_20190129_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='publish_time',
            field=models.CharField(default='29 January 2019, 13:28 PM', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish_time',
            field=models.CharField(default='29 January 2019, 13:28 PM', max_length=100),
        ),
    ]
